version: '3'
services:
    redis:
        container_name: redis
        image: redis:latest
        environment:
            - "TZ=Asia/Taipei"
        restart: always
        ports:
            - 6379:6379

    memcached:
        container_name: memcached
        image: memcached
        environment:
            - "TZ=Asia/Taipei"
        restart: always
        ports:
            - 11211:11211

    dafweb:
        depends_on:
            - redis
            - memcached
        container_name: web
        image: docker-images
        volumes:
            - "($pwd):/var/www/html/yoursourcecodefoldername"
        ports:
            - "7000:80"
        restart: always
