version: '3'
services:
    redis:
        container_name: redis
        image: redis:latest
        environment:
            - "TZ=Asia/Taipei"
        restart: always
        ports:
            - 6379:6379

    memcached:
        container_name: memcached
        image: memcached
        environment:
            - "TZ=Asia/Taipei"
        restart: always
        ports:
            - 11211:11211

    dafweb:
        depends_on:
            - redis
            - memcached
        container_name: web
        image: docker-images
        volumes:
            - "($pwd)/yoursourcecodefoldername:/var/www/html/gamma/yoursourcecodefoldername"
            - "($pwd)/yoursourcecodefoldername/manifest/config/gamma_config.ini:/var/www/html/gamma/yoursourcecodefoldername/app/config/gamma_config.ini"
            - "($pwd)/yoursourcecodefoldername/manifest/config/production_config.ini:/var/www/html/gamma/yoursourcecodefoldername/app/config/production_config.ini"
        ports:
            - "7000:80"
        restart: always
